// App config generated by the Fusabase Console (Project > Apps > WEBDEMO).
// Like a Firebase config object, this is client-side and not a secret:
// access is controlled by security rules and auth, not by hiding these ids.
export const fusabaseConfig = {
  schema: "vito",
  app_name: "WEBDEMO",
  app_type: "WEB",
  app_id: "58D64B0C789F4307E063F40D1FAC19AD",
  objs_type: "dbfs",
  project_id: "58D6470B91BF4302E063F40D1FAC8719",
  storage_bucket: "dbfs_YALOWOGCQGWKBQN",
  auth_type: "base",
  auth_id: "58D6470B91C34302E063F40D1FAC8719",
  ords_host: "https://oracle.vvanhecke.be/ords/vito/",
};
